# Configuração Padrão
spring:
  profiles:
    active: dev

server:
  port: 8081

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor: TRACE
      springframework: DEBUG
      springdoc: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    urls:
      - name: 'API'
        url: /api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,loggers
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      all: true

---
# Configuração para o Perfil 'dev' (Ambiente Local)
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/kanban
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  sql:
    init:
      mode: always

---
# Configuração para o Perfil 'docker' (Contêiner Docker)
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://db:5432/kanban
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  sql:
    init:
      mode: always

server:
  port: 8080