spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kanban
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20        # número máximo de conexões simultâneas
      minimum-idle: 5              # conexões mínimas ociosas
      idle-timeout: 30000          # tempo máximo que a conexão pode ficar ociosa
      max-lifetime: 1800000        # tempo máximo de vida da conexão
      connection-timeout: 30000    # timeout de aquisição da conexão

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true     # formata o SQL gerado
    show-sql: true           # mostra o SQL no console

  sql:
    init:
      mode: always            # garante que scripts SQL sejam executados se houver

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG            # mostra SQL gerado pelo Hibernate
        type:
          descriptor: TRACE   # mostra detalhes dos tipos de dados

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,loggers
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      all: true

