global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kanban-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080'] # ou localhost:8080 se rodando local
